name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./my_react_app   # chemin vers ton dossier de projet
          file:    ./my_react_app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/my-react-app:latest
